# Generated by Django 5.0.6 on 2024-07-07 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsManagement', '0002_evento_cupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventsManagement.evento'),
        ),
    ]
